### ISSUE TITLE
Find alternative to duplicating config variables for replication factors

### ISSUE THREAD

**Issue by OneCricketeer** [OneCricketeer/cp-ansible-vagrant#2]
In #3 , I copied out some config variables and referenced them in the same file. 

Ideally, Ansible/Vagrant should be able to just let me set the variables like 

```yaml
kafka:
  broker:
    config:
      offsets.topic.replication.factor: 1
```

However, this appears to overwrite the entire `kafka.broker` subtree, and not only `kafka.broker.config`, so the playbook fails trying to first find `kafka.broker.group` (and other sub-nodes)
